CALLBACK_CALC_REQUEST = "CALLBACK_CALC_REQUEST"
CALLBACK_CALC_REQUEST_CANCEL = "CALLBACK_CALC_REQUEST_CANCEL"

CALLBACK_SHOW_TEST_COURSE = "CALLBACK_SHOW_TEST_COURSE"
CALLBACK_INVOICE_COURSE_1 = "CALLBACK_INVOICE_COURSE_1"
CALLBACK_INVOICE_COURSE_2 = "CALLBACK_INVOICE_COURSE_2"

INVOICE_PAYLOAD_COURSE_1 = "INVOICE_PAYLOAD_COURSE_1"
INVOICE_PAYLOAD_COURSE_2 = "INVOICE_PAYLOAD_COURSE_2"
