name: Deploy to vps server

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VDS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.REMOTE_USER }}

          script: |
            cd /var/www/ecom_bot
            git fetch
            git pull
            git reset --hard origin/master

            source ./venv/bin/activate
            poetry install
            alembic upgrade head

            supervisorctl restart ecom_bot
